### ISSUE TITLE
 Error: No Fast Downward compilation found. Compile Fast Downward before running this script.

### ISSUE THREAD

**Issue by ShiqinHuo** [aig-upf/smart-carpooling-demo#5]
I intended to run your demo in my own laptop, but it seems error messages for compiling occurred. Hopefully, you guys could help me out..

Compiling problem: 

PycharmProjects/temporal-planning/bin/compileSHE tdom.pddl tins.pddl > dom.pddl 2> ins.pddl

Error: No Fast Downward compilation found. Compile Fast Downward before running this script.

**Comment by ertsiger** [comment]
Hi,

have you followed the instructions for compiling the temporal planning repository? It looks like you compiled the transformations from temporal to classical planning, but not Fast Downward. Check this: https://github.com/aig-upf/temporal-planning/blob/master/README.md#fd-compilation.

If you keep having problems, let us know.
